language: swift
osx_image: xcode9.3beta

git:
  submodules: false

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=DITranquillity.xcworkspace
    - FRAMEWORK_NAME=DITranquillity
    - IOS_SDK=iphonesimulator
    - OSX_SDK=macosx
    - TVOS_SDK=appletvsimulator
  matrix:
    # - DESTINATION="OS=8.4,name=iPhone 5" SCHEME="DITranquillity-iOS" SDK="$IOS_SDK" PLATFORM="iOS" ACTION="test"
    - DESTINATION="OS=9.3,name=iPhone 6" SCHEME="DITranquillity-iOS" SDK="$IOS_SDK" PLATFORM="iOS" ACTION="test" ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=NO
    # - DESTINATION="OS=10.3,name=iPhone 6S Plus" SCHEME="DITranquillity-iOS" SDK="$IOS_SDK" PLATFORM="iOS" ACTION="test"
    - DESTINATION="OS=11.2,name=iPhone 8 Plus" SCHEME="DITranquillity-iOS" SDK="$IOS_SDK" PLATFORM="iOS" ACTION="test" ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES
    - DESTINATION="arch=x86_64" SCHEME="DITranquillity-OSX" SDK="$OSX_SDK" PLATFORM="Mac" ACTION="build" ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=NO
    - DESTINATION="OS=9.2,name=Apple TV 1080p" SCHEME="DITranquillity-tvOS" SDK="$TVOS_SDK" PLATFORM="tvOS" ACTION="build" ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=NO
    - DESTINATION="OS=10.0,name=Apple TV 1080p" SCHEME="DITranquillity-tvOS" SDK="$TVOS_SDK" PLATFORM="tvOS" ACTION="build" ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=NO
    - DESTINATION="OS=11.0,name=Apple TV 1080p" SCHEME="DITranquillity-tvOS" SDK="$TVOS_SDK" PLATFORM="tvOS" ACTION="build" ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=NO
before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.28.0/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - rm Carthage.pkg
script:
  - set -o pipefail
  - open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
  - carthage update
  - xcodebuild "$ACTION" -workspace "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ENABLE_TESTABILITY=$ENABLE_TESTABILITY ONLY_ACTIVE_ARCH=$ONLY_ACTIVE_ARCH
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never